{ pkgs, config, lib, ... }:

{
  wayland.windowManager.hyprland = {
    enable = true;
    xwayland.enable = true;

    settings = {
      monitor = [ ",preferred,auto,1" ];

      # Colors generated by wallust land here after your first wallpaper pick
      source = [ "~/.config/hypr/colors.conf" ];

      "$mainMod" = "SUPER";

      # hypridle is started by its own systemd user service (see
      # desktop/hypridle.nix) rather than here, to avoid double-launching it.
      # If it doesn't auto-start on your system, add "hypridle" to this list
      # as a fallback (a known home-manager/systemd quirk without UWSM).
      exec-once = [
        "waybar"
        "swww-daemon"
        "waypaper --restore"
        "dunst"
        "wl-paste --watch cliphist store"
        "/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1"
      ];

      env = [
        "XCURSOR_THEME,Sweet-cursors"
        "XCURSOR_SIZE,24"
        "QT_QPA_PLATFORMTHEME,qt5ct"
      ];

      input = {
        kb_layout = "us";
        follow_mouse = 1;
        sensitivity = 0;
        touchpad = {
          natural_scroll = true;
        };
      };

      general = {
        gaps_in = 5;
        gaps_out = 12;
        border_size = 2;
        "col.active_border" = "$active_border $inactive_border 45deg";
        "col.inactive_border" = "$inactive_border";
        layout = "dwindle";
        resize_on_border = true;
      };

      decoration = {
        rounding = 10;
        active_opacity = 0.92;
        inactive_opacity = 0.85;
        blur = {
          enabled = true;
          size = 8;
          passes = 4;
          new_optimizations = true;
          ignore_opacity = true;
          xray = false;
        };
        drop_shadow = true;
        shadow_range = 12;
      };

      animations = {
        enabled = true;
        bezier = [ "myBezier, 0.05, 0.9, 0.1, 1.05" ];
        animation = [
          "windows, 1, 5, myBezier"
          "fade, 1, 5, default"
          "workspaces, 1, 5, default"
        ];
      };

      dwindle = {
        pseudotile = true;
        preserve_split = true;
      };

      # Per-app opacity overrides
      windowrulev2 = [
        "opacity 0.90 0.85,class:^(kitty)$"
        "opacity 0.95 0.90,class:^(thunar)$"
      ];

      bind = [
        "$mainMod, Return, exec, kitty"
        "$mainMod, Q, killactive"
        "$mainMod, E, exec, thunar"
        "$mainMod, R, exec, rofi -show drun"
        "$mainMod, V, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy"
        "$mainMod, L, exec, hyprlock"
        "$mainMod SHIFT, Q, exec, wlogout -b 5"
        ", Print, exec, grim -g \"$(slurp)\" - | swappy -f -"

        "$mainMod, 1, workspace, 1"
        "$mainMod, 2, workspace, 2"
        "$mainMod, 3, workspace, 3"
        "$mainMod, 4, workspace, 4"
        "$mainMod SHIFT, 1, movetoworkspace, 1"
        "$mainMod SHIFT, 2, movetoworkspace, 2"
        "$mainMod SHIFT, 3, movetoworkspace, 3"
        "$mainMod SHIFT, 4, movetoworkspace, 4"
      ];

      bindm = [
        "$mainMod, mouse:272, movewindow"
        "$mainMod, mouse:273, resizewindow"
      ];

      binde = [
        ", XF86AudioRaiseVolume, exec, pamixer -i 5"
        ", XF86AudioLowerVolume, exec, pamixer -d 5"
        ", XF86MonBrightnessUp, exec, brightnessctl set +10%"
        ", XF86MonBrightnessDown, exec, brightnessctl set 10%-"
      ];

      bindl = [
        ", XF86AudioMute, exec, pamixer -t"
        ", XF86AudioPlay, exec, playerctl play-pause"
        ", XF86AudioNext, exec, playerctl next"
        ", XF86AudioPrev, exec, playerctl previous"
      ];
    };
  };
  # NOTE: hypr/colors.conf is a wallust target — seeded once (writably) by
  # the activation script in style/wallust.nix, not managed here.
}
